### ISSUE TITLE
Game broken

### ISSUE THREAD

**Issue by paromitaroy** [prgithubschool/github-games-mk3jamie#1]
When attempting to access this at https://prgithubschool.github.io/github-games-mk3jamie, I am getting a 404. This could be caused by a couple of things:

- GitHub Pages needs to be enabled on the  branch. You can fix this in the repository settings.
- The **index.html** file is incorrectly named **inde.html**. We will fix this together in class.

Can you fix the first bullet, please?

**Comment by mk3jamie** [comment]
I've enabled pages and fixed the index.html page. The game is working as expected
